version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    tty: true
    networks:
      - network
    command: sleep infinity

networks:
  network:
    driver: bridge
