version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    tty: true
    networks:
      - network
    command: sleep infinity

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/frontend/node_modules
    env_file:
      - ./frontend/.env
    tty: true
    command: sleep infinity
    networks:
      - network

volumes:
  node_modules:
networks:
  network:
    driver: bridge
